- yopass.go
> Log err on failure to set

- Dockerfile
- README.md
- cmd/yopass/main.go
- pkg/yopass/handlers.go
- pkg/yopass/memcached.go
Use command line flags instead of environment variables.
Add ability to specify port
> Migrate to command line flags

- Dockerfile
> Specify which version of website to run.

- .travis.yml
> curl before running test.

- cmd/yopass/main.go
Thanks for the great tool!
We would like yopass to listen on 127.0.0.1. This PR adds the corresponding flag.
> Add -address flag

- website/src/Create.tsx
Pick numbers within range from generated array using rejection sampling.
Fixed #173
> Switch key generation to Crypto.getRandomValues

- website/src/Create.tsx
* Prevent out of range when selecting password characters.
* Increase password length to 22 characters.
> Improve password generation

- deploy/aws-lambda/main.go
- deploy/aws-lambda/serverless.yml
Read from environment vars, default to 1024 if unset.
Update serverless.yml to include env var set to 1024.
Fixes #263
> fix, add maxLength parameter to lambda deploy

- README.md
- cmd/yopass/main.go
- go.mod
- go.sum
- pkg/yopass/redis.go
- pkg/yopass/redis_test.go
This change adds a new `Database` implementation for storing encrypted secrets in Redis - which provides a key/value store with persistence of values between restarts.
Either implementation can be chosen by specifying the according command line flag.
> Implement Redis database as alternative storage

- pkg/yopass/yopass.go
- pkg/yopass/yopass_test.go
- website/src/Create.tsx
- website/src/DisplaySecret.test.tsx
- website/src/DisplaySecret.tsx
- website/src/Error.tsx
- website/src/Upload.tsx
> Make one-time downloads optionally

- website/public/yopass.svg
> replace symlink with file

- go.mod
- go.sum
- pkg/yopass/yopass.go
This is a repeat of the work I did in #165. I have more attention to spare for this right now this time. This upgrades to the very latest UUID.
> check the error from NewV4()

- website/package.json
- website/src/App.tsx
- website/src/Routes.tsx
- website/src/createSecret/CreateSecret.tsx
- website/src/createSecret/Form.tsx
- website/src/createSecret/Lifetime.tsx
- website/src/createSecret/Upload.tsx
- website/src/displaySecret/DisplaySecret.tsx
- website/src/displaySecret/Download.tsx
- website/src/displaySecret/Error.tsx
- website/src/displaySecret/Result.tsx
- website/src/displaySecret/Secret.tsx
- website/src/index.tsx
- website/src/shared/Attribution.tsx
- website/src/shared/Features.tsx
- website/src/shared/Header.tsx
- website/src/shared/Loading.tsx
- website/src/utils/utils.tsx
- website/src/yopass.d.ts
Remove React.FC
Remove react imports
Add import linting
> Cleanup imports

- website/src/createSecret/CreateSecret.tsx
- website/src/createSecret/Upload.tsx
> Tidy up rendering

- website/src/displaySecret/Secret.tsx
> Do not download multiple times

- deploy/yopass-k8.yaml
Using recommendations from here: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
> Update apiVersion, labels, and formatting

- website/src/createSecret/CreateSecret.tsx
- website/src/displaySecret/DisplaySecret.tsx
Solves issue [#868](https://github.com/jhaals/yopass/issues/868)
> feat: Disable grammarly extension and spellcheck attribute on textfields

- deploy/yopass-k8.yaml
Limits and requests have been added to limit the service.
> Update yopass-k8.yaml (added limits and requests)

- website/package.json
- website/src/createSecret/CreateSecret.tsx
- website/src/displaySecret/Error.tsx
- website/src/shared/Expiration.tsx
- website/src/shared/Features.tsx
- website/src/shared/Header.tsx
- website/yarn.lock
Signed-off-by: Johan Haals <johan.haals@gmail.com>
> Reduce makeStyles in favour of sx prop

- website/package.json
- website/src/createSecret/CreateSecret.tsx
- website/src/displaySecret/DeleteSecret.tsx
- website/src/utils/utils.tsx
- website/yarn.lock
Signed-off-by: Johan Haals <johan.haals@gmail.com>
> Bump typescript to 4.5.2

- README.md
See #1566 for french translation contribution
> feat(translations): add french translation url in readme

- next/public/locales/en/common.json
- website/public/locales/en.json
Thanks for a nice tool! :pray: Here's my first contribution, the same day I read that our organization had taken Yopass into usage. :slightly_smiling_face:
> Fix some typos in the English UI strings

- README.md
Hi,
I've added the Dutch translation file to the project.
Best regards,
Kevin
> Added Dutch translation file

- README.md
> docs: add link to russian translation to readme

- add: Link to Swedish translation in README.md
Hello,
We thought we'd share our translation used at Norrköping's municipality.
> Update and rename README.md to add link to Swedish translation

- cmd/yopass-server/main.go
> implement graceful shutdown

- cmd/yopass-server/main.go
- cmd/yopass-server/main_test.go
Add tests for database setup.
Replace usage of deprecated collectors
> Add tests for database setup

- README.md
- cmd/yopass-server/main.go
- pkg/server/server.go
+ OPTIONS routes
+  config option to set CORS allow-origin
Fixes #2651
> [FEATURE] add OPTIONS endpoints

- website/src/utils/utils.tsx
Demo sites need updated cors in order to function. 
Reverting for now.
fixes #2731
> Revert "Fix: set Content-type to JSON"

- README.md
I'm adding Indonesian language
> adding Bahasa Indonesia translation

- pkg/server/server.go
- pkg/server/server_test.go
- website/src/features/CreateSecret.tsx
- website/src/features/Upload.tsx
- website/src/shared/context/ConfigContext.tsx
- website/tests/force-onetime-secrets.spec.ts
- website/tests/helpers/mock-api.ts
Introduce support for enforcing one time secrets by specifying the command line flag in the server. fixes #3014
> Add support for --force-onetime-secrets
